const DiscordJS = require('discord.js');
module.exports = {
    minArgs: 0,
    maxArgs: 0,
    aliases: ['r255'],
    description: "pick a random cannon",
    async callback ({ message, args, client }) {

        let randomrange = Math.floor((Math.random() * 2000) + 500); //min 500 max 2000
        let chunks = (Math.floor(randomrange / 16))

        let speed = ["1.0s", "1.5s", "2.0s", "3.0s"]
                const randomspeed = speed[(Math.random() * speed.length) | 0]

        let barrel = ["Stair", "Trapdoor", "Fence", "LYC", "Cactus", "Enderchest", "Head", "Corner cubic", "Center cubic", "Straight cubic", "Inverted stair", "Chest cubic", "Straight shooter"]
            const randombarrel = barrel[(Math.random() * barrel.length) | 0]

        let sand = "255"

        let nuke = ["Webbust", "Gametick nuke"]
            const randomnuke = nuke[(Math.random() * nuke.length) | 0]

        let overstack = ["2", "4", "6", "8"]
            const randomoverstack = overstack[(Math.random() * overstack.length) | 0]

                const embed = new DiscordJS.MessageEmbed()
                .setTitle(`🌴 ${randomspeed} ${sand} Stacker 🌴`)
                .setDescription(`This cannon has been randomly generated, goodluck!`)
                .addFields(
                    { name: 'Speed:', value: `${randomspeed}`, inline: true },
                    { name: 'Barrel:', value: `${randombarrel}`, inline: true },
                    { name: 'Sand', value: `${sand}`, inline: true },
                    // new line
                    { name: 'Range:', value: `${randomrange} blocks \n ${chunks} chunks`, inline: true },
                    { name: 'Nuke:', value: `${randomnuke}`, inline: true },
                    { name: 'Overstacker:', value: `${randomoverstack} blocks`, inline: true },
                    //new line
                    { name: 'Early version!', value: "If you want anything added/updated use ``c.suggest``", inline: false })
                .setThumbnail(process.env.logo)
                .setFooter(process.env.botversion + `・Generated by ${message.author.tag}`)
                .setColor(process.env.embedcolor)

            message.channel.send(embed)

    }
}